"""entity engine_full sorting_key primary_key

Revision ID: 0a444e337164
Revises: 6ab50cc9755f
Create Date: 2026-07-26 19:37:25.475867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a444e337164"
down_revision: Union[str, Sequence[str], None] = "6ab50cc9755f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entities", sa.Column("engine_full", sa.Text(), server_default="", nullable=False))
    op.add_column("entities", sa.Column("sorting_key", sa.Text(), server_default="", nullable=False))
    op.add_column("entities", sa.Column("primary_key", sa.Text(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entities", "primary_key")
    op.drop_column("entities", "sorting_key")
    op.drop_column("entities", "engine_full")
    # ### end Alembic commands ###
