"""labelrow source

Revision ID: 6ab50cc9755f
Revises: fae779e73740
Create Date: 2026-07-25 18:53:25.206524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab50cc9755f'
down_revision: Union[str, Sequence[str], None] = 'fae779e73740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('source', sa.String(length=16), server_default='manual', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'source')
    # ### end Alembic commands ###
