"""baseline

Revision ID: fae779e73740
Revises:
Create Date: 2026-07-25 18:04:47.066202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae779e73740'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster', sa.String(length=255), nullable=False),
    sa.Column('database', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('engine', sa.String(length=255), nullable=False),
    sa.Column('ddl', sa.Text(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('upstream', sa.JSON(), nullable=False),
    sa.Column('downstream', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster', 'database', 'name')
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster', sa.String(length=255), nullable=False),
    sa.Column('database', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster', 'database', 'table_name', 'key')
    )
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_id', sa.Integer(), nullable=False),
    sa.Column('dst_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dst_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edges')
    op.drop_table('labels')
    op.drop_table('entities')
    # ### end Alembic commands ###
